#pragma once
#include <wx/event.h>
wxDECLARE_EVENT(EVT_ORGANIZATION_CHANGED, wxCommandEvent);
wxDECLARE_EVENT(EVT_ACTIVE_ORG_CHANGED, wxCommandEvent);
wxDECLARE_EVENT(EVT_ACTIVE_UNIT_CHANGED, wxCommandEvent);
wxDECLARE_EVENT(EVT_DATABASE_CHANGED, wxCommandEvent);
wxDECLARE_EVENT(EVT_DIR_CHANGED, wxCommandEvent);
wxDECLARE_EVENT(EVT_ENTERED_CODE_EXISTS, wxCommandEvent);