#include "CustomEvents.h"

wxDEFINE_EVENT(EVT_ORGANIZATION_CHANGED, wxCommandEvent);
wxDEFINE_EVENT(EVT_ACTIVE_ORG_CHANGED, wxCommandEvent);
wxDEFINE_EVENT(EVT_ACTIVE_UNIT_CHANGED, wxCommandEvent);
wxDEFINE_EVENT(EVT_DATABASE_CHANGED, wxCommandEvent);
wxDEFINE_EVENT(EVT_DIR_CHANGED, wxCommandEvent);
wxDEFINE_EVENT(EVT_ENTERED_CODE_EXISTS, wxCommandEvent);