#pragma once
enum DB_COLUMN_IDS
{
	DB_COLUMN_ID,
	DB_COLUMN_OWNER,
	DB_COLUMN_RECEIVER,
	DB_COLUMN_TRANSPORT,
	DB_COLUMN_DATE,
	DB_COLUMN_CODE,
	DB_COLUMN_REGNUM,
	DB_COLUMN_AMOUNT_FORMED,
	DB_COLUMN_AMOUNT_RECEIVED_ORG,
	DB_COLUMN_AMOUNT_RECEIVED_PHYS,
	DB_COLUMN_AMOUNT_USED,
	DB_COLUMN_AMOUNT_DEFUSED,
	DB_COLUMN_AMOUNT_SELFSTORAGE,
	DB_COLUMN_AMOUNT_BURIAL,
	DB_COLUMN_AMOUNT_TRANSFER_USED,
	DB_COLUMN_AMOUNT_TRANSFER_DEFUSED,
	DB_COLUMN_AMOUNT_TRANSFER_STORAGE,
	DB_COLUMN_AMOUNT_TRANSFER_BURIAL,
	DB_COLUMN_AMOUNT_SELFSTORAGE_FULL,
	DB_COLUMN_WASTE_NORM,
	DB_COLUMN_STRUCTURAL_POD10,
	DB_COLUMN_ENTRYDATE,
	DB_COLUMN_STRUCTURAL_POD9,
	DB_COLUMN_SYMBOLS_AFTER_COMA,
	DB_COLUMN_INITIAL,
	DB_COLUMN_UNIT_ID,
	DB_COLUMN_MAXIDS
};

